export const adminSummaryCards = [
  {
    id: 'pending-events',
    label: 'Sự kiện chờ duyệt',
    value: '12',
    tone: 'bg-amber-100 text-amber-700',
  },
  {
    id: 'active-accounts',
    label: 'Tài khoản đang hoạt động',
    value: '1,284',
    tone: 'bg-emerald-100 text-emerald-700',
  },
  {
    id: 'today-notices',
    label: 'Thông báo hôm nay',
    value: '08',
    tone: 'bg-blue-100 text-blue-700',
  },
];

export const pendingEvents = [
  {
    id: 'lc-cntt-01',
    title: 'Ngày hội Kỹ năng số cho sinh viên năm nhất',
    unit: 'Liên chi Đoàn Khoa Công nghệ thông tin',
    time: '08:00 - 11:30, 06/04/2026',
    location: 'Hội trường F',
    status: 'Chờ duyệt',
    category: 'Kỹ năng',
    description: 'Chương trình tập huấn kỹ năng số, an toàn thông tin cơ bản và cộng tác trực tuyến cho sinh viên năm nhất.',
    plan: 'Có kế hoạch tổ chức, poster truyền thông và timeline chi tiết.',
  },
  {
    id: 'lc-co-khi-02',
    title: 'Hành trình xanh làm sạch khuôn viên',
    unit: 'Liên chi Đoàn Khoa Cơ khí',
    time: '07:00 - 10:30, 09/04/2026',
    location: 'Khu B - sân trung tâm',
    status: 'Chờ duyệt',
    category: 'Tình nguyện',
    description: 'Hoạt động vệ sinh khuôn viên, phân loại rác và tuyên truyền bảo vệ môi trường cho sinh viên.',
    plan: 'Có phân công đầu việc theo ca, khu vực phụ trách và phương án truyền thông.',
  },
  {
    id: 'lc-dien-03',
    title: 'Diễn đàn sáng tạo trẻ Bách Khoa',
    unit: 'Liên chi Đoàn Khoa Điện',
    time: '18:30 - 21:00, 12/04/2026',
    location: 'Phòng hội thảo A3',
    status: 'Chờ duyệt',
    category: 'Học thuật',
    description: 'Diễn đàn chia sẻ ý tưởng sáng tạo, mô hình nghiên cứu và kết nối sinh viên đam mê công nghệ.',
    plan: 'Đã đính kèm kịch bản chương trình, danh sách diễn giả và dự toán kinh phí.',
  },
];

export const userAccounts = [
  {
    id: 'u001',
    fullName: 'Nguyễn Đỗ Thắng',
    email: 'nguyendothang@sv.dut.udn.vn',
    studentId: '102230046',
    role: 'Sinh viên',
    faculty: 'CNTT',
    status: 'Hoạt động',
  },
  {
    id: 'u002',
    fullName: 'Trần Minh Quân',
    email: 'tranminhquan@sv.dut.udn.vn',
    studentId: '102220115',
    role: 'Liên chi Đoàn',
    faculty: 'Cơ khí',
    status: 'Hoạt động',
  },
  {
    id: 'u003',
    fullName: 'Lê Thu Hà',
    email: 'lethuha@dut.udn.vn',
    studentId: 'CB001',
    role: 'Đoàn trường',
    faculty: 'Văn phòng Đoàn',
    status: 'Hoạt động',
  },
  {
    id: 'u004',
    fullName: 'Phạm Gia Hưng',
    email: 'phamgiahung@sv.dut.udn.vn',
    studentId: '102210087',
    role: 'Sinh viên',
    faculty: 'Điện',
    status: 'Tạm khóa',
  },
];

export const adminNotifications = [
  {
    id: 'noti-01',
    title: 'Nhắc bổ sung hồ sơ sự kiện',
    audience: 'Liên chi Đoàn Khoa Cơ khí',
    channel: 'Thông báo hệ thống',
    sentAt: '14/04/2026 08:30',
    status: 'Đã gửi',
  },
  {
    id: 'noti-02',
    title: 'Cập nhật lịch kiểm tra điểm danh QR',
    audience: 'Toàn bộ cán bộ Đoàn - Hội',
    channel: 'Email nội bộ',
    sentAt: '14/04/2026 10:00',
    status: 'Đã lên lịch',
  },
  {
    id: 'noti-03',
    title: 'Mở đợt đánh giá sự kiện tháng 4',
    audience: 'Sinh viên toàn trường',
    channel: 'Thông báo hệ thống',
    sentAt: '14/04/2026 11:20',
    status: 'Đã gửi',
  },
];

export const systemSettings = [
  {
    id: 'semester',
    label: 'Học kỳ đang áp dụng',
    value: 'Học kỳ 2 năm học 2025 - 2026',
    description: 'Dùng để gắn dữ liệu điểm rèn luyện, lịch đăng ký và báo cáo thống kê.',
  },
  {
    id: 'event-window',
    label: 'Khoảng mở đăng ký sự kiện',
    value: 'Từ 7 ngày trước khi sự kiện diễn ra',
    description: 'Giới hạn thời điểm sinh viên được phép nhìn thấy và đăng ký hoạt động.',
  },
  {
    id: 'attendance-radius',
    label: 'Bán kính điểm danh QR',
    value: '150 mét',
    description: 'Áp dụng cho hoạt động yêu cầu định vị khi check-in.',
  },
  {
    id: 'evidence-deadline',
    label: 'Hạn nộp minh chứng',
    value: '48 giờ sau khi sự kiện kết thúc',
    description: 'Quy định thời hạn hệ thống cho phép nộp minh chứng tham gia.',
  },
];

export const auditLogs = [
  {
    id: 'log-01',
    actor: 'Lê Thu Hà',
    role: 'Đoàn trường',
    action: 'Duyệt sự kiện "Hành trình xanh làm sạch khuôn viên"',
    time: '10/06/2026 10:30',
    level: 'Cao',
  },
  {
    id: 'log-02',
    actor: 'Nguyễn Văn Dũng',
    role: 'Quản trị viên',
    action: 'Cấp quyền Liên chi Đoàn cho tài khoản Nguyễn Minh Anh',
    time: '10/06/2026 09:15',
    level: 'Cao',
  },
  {
    id: 'log-03',
    actor: 'Lê Thu Hà',
    role: 'Đoàn trường',
    action: 'Khóa tài khoản sinh viên Phạm Gia Hưng do vi phạm quy chế điểm danh',
    time: '10/06/2026 08:00',
    level: 'Cao',
  },
  {
    id: 'log-04',
    actor: 'Trần Minh Quân',
    role: 'Liên chi Đoàn',
    action: 'Tạo mới sự kiện "Hội thảo Công nghệ và Tương lai"',
    time: '09/06/2026 16:45',
    level: 'Trung bình',
  },
  {
    id: 'log-05',
    actor: 'Nguyễn Văn Dũng',
    role: 'Quản trị viên',
    action: 'Cập nhật cấu hình bán kính điểm danh QR từ 100m lên 150m',
    time: '09/06/2026 14:20',
    level: 'Trung bình',
  },
  {
    id: 'log-06',
    actor: 'Lê Thu Hà',
    role: 'Đoàn trường',
    action: 'Duyệt chứng nhận sự kiện "Chiến dịch Mùa hè xanh"',
    time: '08/06/2026 11:10',
    level: 'Cao',
  },
  {
    id: 'log-07',
    actor: 'Nguyễn Văn Dũng',
    role: 'Quản trị viên',
    action: 'Khôi phục mật khẩu mặc định cho sinh viên Võ Khánh Linh',
    time: '08/06/2026 09:30',
    level: 'Thấp',
  },
  {
    id: 'log-08',
    actor: 'Trần Minh Quân',
    role: 'Liên chi Đoàn',
    action: 'Cập nhật tài liệu minh chứng cho sự kiện Khoa CNTT',
    time: '06/06/2026 15:00',
    level: 'Thấp',
  },
  {
    id: 'log-09',
    actor: 'Lê Thu Hà',
    role: 'Đoàn trường',
    action: 'Thay đổi trạng thái học kỳ áp dụng thành Học kỳ 2 năm học 2025 - 2026',
    time: '04/06/2026 10:00',
    level: 'Cao',
  },
  {
    id: 'log-10',
    actor: 'Nguyễn Văn Dũng',
    role: 'Quản trị viên',
    action: 'Sao lưu dữ liệu hệ thống định kỳ tuần 1 tháng 6',
    time: '04/06/2026 02:00',
    level: 'Trung bình',
  },
  {
    id: 'log-11',
    actor: 'Trần Minh Quân',
    role: 'Liên chi Đoàn',
    action: 'Gửi thông báo nhắc nhở nộp minh chứng cho Khoa Cơ khí',
    time: '30/05/2026 13:40',
    level: 'Thấp',
  },
  {
    id: 'log-12',
    actor: 'Nguyễn Văn Dũng',
    role: 'Quản trị viên',
    action: 'Cập nhật cấu hình bảo mật mật khẩu tối thiểu 6 ký tự',
    time: '15/05/2026 11:00',
    level: 'Trung bình',
  },
  {
    id: 'log-13',
    actor: 'Lê Thu Hà',
    role: 'Đoàn trường',
    action: 'Khóa tài khoản Liên chi Đoàn Khoa Điện do thông tin sai lệch',
    time: '15/05/2026 09:15',
    level: 'Cao',
  },
  {
    id: 'log-14',
    actor: 'Nguyễn Văn Dũng',
    role: 'Quản trị viên',
    action: 'Xuất báo cáo hoạt động Đoàn thanh niên Quý 1/2026',
    time: '15/04/2026 16:30',
    level: 'Trung bình',
  }
];
