export const lienChiSummaryCards = [
  {
    id: 'my-events',
    label: 'Sự kiện đang quản lý',
    value: '06',
    tone: 'bg-blue-100 text-blue-700',
  },
  {
    id: 'pending-evidences',
    label: 'Minh chứng chờ duyệt',
    value: '14',
    tone: 'bg-amber-100 text-amber-700',
  },
  {
    id: 'registered-students',
    label: 'Sinh viên đã đăng ký',
    value: '482',
    tone: 'bg-emerald-100 text-emerald-700',
  },
];

export const lienChiEvents = [
  {
    id: 'cntt-ky-nang-so',
    title: 'Ngày hội kỹ năng số cho sinh viên năm nhất',
    status: 'Chờ duyệt',
    category: 'Kỹ năng',
    time: '08:00 - 11:30, 06/04/2026',
    location: 'Hội trường F',
    organizer: 'Liên chi Đoàn Khoa Công nghệ thông tin',
    registrations: 148,
    capacity: 200,
    attendanceMethod: 'QR + GPS',
    registrationMode: 'Mở công khai',
    timeline: [
      '07:30 - Check-in và ổn định lực lượng',
      '08:00 - Khai mạc chương trình',
      '10:45 - Tổng kết và giao nhiệm vụ',
    ],
    note: 'Hồ sơ đang chờ Đoàn trường xét duyệt lần cuối.',
  },
  {
    id: 'cntt-chu-nhat-xanh',
    title: 'Chủ nhật xanh khoa Công nghệ thông tin',
    status: 'Đã duyệt',
    category: 'Tình nguyện',
    time: '07:00 - 10:30, 09/04/2026',
    location: 'Khu B - sân trung tâm',
    organizer: 'Liên chi Đoàn Khoa Công nghệ thông tin',
    registrations: 112,
    capacity: 120,
    attendanceMethod: 'QR',
    registrationMode: 'Mở công khai',
    timeline: [
      '06:45 - Tập trung theo tổ',
      '07:00 - Phân công khu vực',
      '10:00 - Tổng hợp kết quả',
    ],
    note: 'Sự kiện đã mở cho sinh viên đăng ký.',
  },
  {
    id: 'cntt-seminar-ai',
    title: 'Seminar AI và đạo đức số',
    status: 'Cần chỉnh sửa',
    category: 'Học thuật',
    time: '18:30 - 20:30, 12/04/2026',
    location: 'Phòng hội thảo A3',
    organizer: 'Liên chi Đoàn Khoa Công nghệ thông tin',
    registrations: 64,
    capacity: 150,
    attendanceMethod: 'QR + GPS',
    registrationMode: 'Đăng ký có xét duyệt',
    timeline: [
      '18:00 - Đón khách mời',
      '18:30 - Trình bày chuyên đề',
      '20:15 - Hỏi đáp và tổng kết',
    ],
    note: 'Đoàn trường yêu cầu bổ sung kế hoạch truyền thông và file poster.',
  },
];

export const lienChiRegistrations = {
  'cntt-ky-nang-so': [
    {
      id: 'sv001',
      fullName: 'Nguyễn Đỗ Thắng',
      studentId: '102230046',
      className: '23T_Nhat1',
      faculty: 'Công nghệ thông tin',
      status: 'Đã xác nhận',
      attendance: 'Chưa check-in',
    },
    {
      id: 'sv002',
      fullName: 'Phạm Gia Hưng',
      studentId: '102210087',
      className: '21T1',
      faculty: 'Công nghệ thông tin',
      status: 'Chờ xếp lớp',
      attendance: 'Chưa check-in',
    },
  ],
  'cntt-chu-nhat-xanh': [
    {
      id: 'sv003',
      fullName: 'Trần Minh Quân',
      studentId: '102220115',
      className: '22T2',
      faculty: 'Công nghệ thông tin',
      status: 'Đã xác nhận',
      attendance: 'Đã check-in',
    },
    {
      id: 'sv004',
      fullName: 'Lê Thu Hà',
      studentId: '102220099',
      className: '22T3',
      faculty: 'Công nghệ thông tin',
      status: 'Đã xác nhận',
      attendance: 'Đã nộp minh chứng',
    },
  ],
  'cntt-seminar-ai': [],
};

export const lienChiEvidenceRequests = [
  {
    id: 'ev001',
    eventId: 'cntt-chu-nhat-xanh',
    eventTitle: 'Chủ nhật xanh khoa Công nghệ thông tin',
    fullName: 'Lê Thu Hà',
    studentId: '102220099',
    submittedAt: '2026-04-10T02:30:00.000Z',
    evidenceType: 'Link bài đăng',
    evidenceValue: 'https://facebook.com/example-post',
    status: 'Chờ duyệt',
    note: 'Bài đăng tổng hợp hình ảnh của đội tình nguyện.',
  },
  {
    id: 'ev002',
    eventId: 'cntt-chu-nhat-xanh',
    eventTitle: 'Chủ nhật xanh khoa Công nghệ thông tin',
    fullName: 'Nguyễn Hoàng My',
    studentId: '102230088',
    submittedAt: '2026-04-10T03:10:00.000Z',
    evidenceType: 'File ảnh',
    evidenceValue: 'anh-minh-chung-nguyen-hoang-my.png',
    status: 'Chờ duyệt',
    note: 'Ảnh chụp khu vực phân công sau khi hoàn thành.',
  },
  {
    id: 'ev003',
    eventId: 'cntt-ky-nang-so',
    eventTitle: 'Ngày hội kỹ năng số cho sinh viên năm nhất',
    fullName: 'Trần Đức Minh',
    studentId: '102240018',
    submittedAt: '2026-04-07T09:00:00.000Z',
    evidenceType: 'PDF',
    evidenceValue: 'bao-cao-tham-gia.pdf',
    status: 'Cần bổ sung',
    note: 'Thiếu ảnh check-in tại khu vực tổ chức sự kiện.',
  },
];
